# Generated by Django 4.0.3 on 2022-08-16 14:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoInfo',
            fields=[
                ('d_national_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('d_first_name', models.CharField(max_length=25)),
                ('d_last_name', models.CharField(max_length=25)),
                ('d_birthday', models.DateField()),
                ('d_gender', models.CharField(choices=[('wom', 'زن'), ('man', 'مرد'), ('ukw', 'نامشخص')], max_length=8)),
                ('d_educate_rate', models.CharField(choices=[('illit', 'بی سواد'), ('elmnt', 'ابتدایی'), ('dplom', 'دیپلم'), ('tchnc', 'کاردانی'), ('exprt', 'کارشناسی'), ('Mstrs', 'کارشناسی ارشد'), ('Phd', 'دکتری')], max_length=10)),
                ('d_economic_situation', models.CharField(choices=[('low', 'ضعیف'), ('norm', 'متوسط'), ('good', 'خوب'), ('best', 'عالی')], max_length=10)),
                ('d_status_job', models.CharField(choices=[('1', 'موضوعیت ندارد'), ('2', 'بیکار'), ('3', 'کشاورز'), ('4', 'کارگر'), ('5', 'کارمند'), ('6', 'بازنشسته'), ('7', 'آزاد')], max_length=20)),
                ('a_country', django_countries.fields.CountryField(max_length=2)),
                ('a_province', models.CharField(max_length=15)),
                ('a_town', models.CharField(max_length=15)),
                ('a_village', models.CharField(max_length=15)),
                ('a_post_code', models.CharField(max_length=10)),
                ('p_home_phone', models.CharField(max_length=11)),
                ('p_cell_phone', models.CharField(max_length=11)),
                ('p_fax', models.CharField(max_length=11)),
                ('p_work_phone', models.CharField(max_length=11)),
                ('p_cellular_phone', models.CharField(max_length=11)),
                ('p_health_care_proxy_phone', models.CharField(max_length=11)),
                ('p_emergency_phone', models.CharField(max_length=11)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_disease', models.CharField(choices=[('1', 'موضوعیت ندارد'), ('2', 'دیابت'), ('3', 'پرقشارخونی'), ('4', 'بیماری خاص')], max_length=20)),
                ('PCR_test_resul', models.BooleanField(default=False)),
                ('allergy', models.BooleanField(default=False)),
                ('national_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecrf', to='eCRF.demoinfo')),
            ],
        ),
    ]
