# Generated by Django 4.0.3 on 2022-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='PCR_test_resul',
            field=models.CharField(choices=[('False', 'خیر'), ('True', 'بله')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='allergy',
            field=models.CharField(choices=[('False', 'خیر'), ('True', 'بله')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='chronic_disease',
            field=models.CharField(choices=[('1', 'موضوعیت ندارد'), ('2', 'دیابت'), ('3', 'پرفشارخون'), ('4', 'بیماری خاص')], max_length=20),
        ),
    ]
