# Generated by Django 4.0.3 on 2022-08-16 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0002_alter_patienthistory_pcr_test_resul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='PCR_test_resul',
            field=models.CharField(choices=[('Yes', 'بله'), ('No', 'خیر')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='allergy',
            field=models.CharField(choices=[('Yes', 'بله'), ('No', 'خیر')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='national_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecrf', to='eCRF.demoinfo'),
        ),
    ]
