# Generated by Django 4.0.3 on 2022-08-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0003_patienthistory_datetime_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='datetime_modified',
        ),
    ]
