# Generated by Django 4.0.3 on 2022-08-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRF', '0006_alter_patienthistory_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبتنام'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
